dist: trusty

sudo: required

language: python

python:
    - "3.5"

os:
    - linux

install:
    - sudo pip3 install -r requirements.txt
    - sudo apt-get update

script: 
    - sudo bash ci_scripts/test_full_setup.sh
