dist: xenial

sudo: required

language: python

python:
    - "2.7"

os:
    - linux

install:
    - sudo pip install ansible
    - sudo pip install -r requirements.txt
    - sudo apt-get update

script: 
    - sudo bash ci_scripts/test_full_setup.sh
